config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :bills
  resources :comments
  resources :tickets
  devise_for :users

  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new"
    get "sign_up", :to => "devise/registrations#new"
    get "sign_out", :to => "devise/sessions#destroy"
    get "verify_account", :to => "devise/registrations#verify_account"
    get "resend_otp", :to => "devise/registrations#resend_otp"
  end

  get 'all_tickets', :to => "tickets#all_tickets"

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :category, :user_id, :description, :status, :ticket_date
  belongs_to :user
  has_many :comments
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController

  before_filter :authenticate_user, :only => [:destroy]
  
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  respond_to :html ,:json

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Array.new
    if params[:user_id] && params[:next] && params[:prev]
      prev = params[:prev].to_i
      nxt = params[:next].to_i
      usr = User.find(params[:user_id])
      if usr
        @tickets = usr.tickets.order( 'created_at DESC' )[prev..nxt]
        if params[:status] == "All"
          @tickets = usr.tickets.order( 'created_at DESC' )[prev..nxt]
        else
          @tickets = usr.tickets.where(:status => params[:status]).order( 'created_at DESC' )[prev..nxt]
        end
      end
    else
      @tickets = Ticket.all.order( 'created_at DESC' )
    end
    #@tickets = @tickets.reverse
  end

  def all_tickets
      # dateformat = "mm-dd-yyyy"
      from_date = Date.strptime(params[:from_date], "%d-%m-%Y")
      to_date = Date.strptime(params[:to_date], "%d-%m-%Y")
      status_arr = JSON.parse params[:status_arr]
      prev = params[:prev].to_i
      nxt = params[:next].to_i
      puts ":::::::::::::::::::::::::::: DETAILS"
      puts from_date
      puts to_date
      puts status_arr.inspect
      puts status_arr.size
      puts params[:category]

      if status_arr[0] == "All"
        puts "::::::::::::::: count 1 with All"        
        @tickets = Ticket.all.where("created_at > ? and created_at < ? and category = ?", from_date, to_date, params[:category] ).order( 'created_at DESC' )[prev..nxt]
      elsif status_arr.size == 1
        puts "::::::::::::::: count 1 but not All"        
        @tickets = Ticket.all.where("created_at > ? and created_at < ? and category = ? and status = ?", from_date, to_date, params[:category], status_arr[0] ).order( 'created_at DESC' )[prev..nxt]
      elsif status_arr.size == 2
        puts "::::::::::::::: count 2"        
        @tickets = Ticket.all.where("created_at > ? and created_at < ? and category = ? and status = ? or status = ?", from_date, to_date, params[:category], status_arr[0], status_arr[0] ).order( 'created_at DESC' )[prev..nxt]
      end
      # @tickets = Ticket.all
      respond_with @tickets
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)
    #@ticket.user_id = params[:user_id]
    @ticket.ticket_date = DateTime.now
    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:category, :user_id, :description, :status, :ticket_date)
    end
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :ticket_date %><br>
    <%= f.datetime_select :ticket_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>User</th>
      <th>Description</th>
      <th>Status</th>
      <th>Ticket date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.category %></td>
        <td><%= ticket.user_id %></td>
        <td><%= ticket.description %></td>
        <td><%= ticket.status %></td>
        <td><%= ticket.ticket_date %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @ticket.category %>
</p>

<p>
  <strong>User:</strong>
  <%= @ticket.user_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @ticket.description %>
</p>

<p>
  <strong>Status:</strong>
  <%= @ticket.status %>
</p>

<p>
  <strong>Ticket date:</strong>
  <%= @ticket.ticket_date %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>